// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Lodash  = require("lodash");

console.log("Hello World");

var u = {
  x: {
    y: {
      z: 3
    }
  }
};

var json_foo = u.x;

var ocaml_string = "from OCaml";

function call_me(payload) {
  console.log(payload.msg.content + ocaml_string);
  return /* () */0;
}

console.log(call_me);

console.log(json_foo);

var my_array = /* array */[
  1,
  2,
  3,
  4,
  5,
  6
];

function sum(x, y) {
  return x + y | 0;
}

function sum_by_2(param) {
  return 2 + param | 0;
}

console.log($$Array.map(sum_by_2, my_array));

console.log(Lodash.map(my_array, sum_by_2));

var u2 = /* record */[
  /* x */33,
  /* y */22,
  /* z */"hi"
];

var u2_x = 33;

exports.u            = u;
exports.u2           = u2;
exports.json_foo     = json_foo;
exports.u2_x         = u2_x;
exports.ocaml_string = ocaml_string;
exports.call_me      = call_me;
exports.my_array     = my_array;
exports.sum          = sum;
exports.sum_by_2     = sum_by_2;
/*  Not a pure module */
